version: '3.9'
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - K_REVISION=${K_REVISION}
      - K_SERVICE=${K_SERVICE}
      - PGHOST=database
      - PGPORT=${PGPORT}
      - PORT=${PORT}
      - PGUSERNAME=${PGUSERNAME}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
